// src/remotion/lesson/voice-manifest.ts
// GENERATED by scripts/build-lesson-voice.ts — do not hand-edit.
export interface VoiceClip {
  id: string;
  file: string; // relative to public/
  durationInSeconds: number;
}

/** unit id → voice key → that voice's clips for the unit. */
export const CLIPS_BY_UNIT: Record<string, Record<string, VoiceClip[]>> = {
  "mul-skip": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-skip/ramlah/ask.mp3",
        "durationInSeconds": 2.74
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-skip/ramlah/groups.mp3",
        "durationInSeconds": 5.898
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-skip/ramlah/count.mp3",
        "durationInSeconds": 11.238
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-skip/ramlah/trick.mp3",
        "durationInSeconds": 7.338
      }
    ]
  },
  "mul-3-4": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-3-4/ramlah/ask.mp3",
        "durationInSeconds": 2.879
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-3-4/ramlah/groups.mp3",
        "durationInSeconds": 5.48
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-3-4/ramlah/count.mp3",
        "durationInSeconds": 10.077
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-3-4/ramlah/trick.mp3",
        "durationInSeconds": 6.269
      }
    ]
  },
  "mul-tens": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-tens/ramlah/ask.mp3",
        "durationInSeconds": 2.694
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-tens/ramlah/groups.mp3",
        "durationInSeconds": 6.362
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-tens/ramlah/count.mp3",
        "durationInSeconds": 9.613
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-tens/ramlah/trick.mp3",
        "durationInSeconds": 9.102
      }
    ]
  },
  "add-2d-noregroup": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-2d-noregroup/ramlah/ask.mp3",
        "durationInSeconds": 2.879
      },
      {
        "id": "build",
        "file": "lesson-voice/add-2d-noregroup/ramlah/build.mp3",
        "durationInSeconds": 4.83
      },
      {
        "id": "regroup",
        "file": "lesson-voice/add-2d-noregroup/ramlah/regroup.mp3",
        "durationInSeconds": 7.848
      },
      {
        "id": "written",
        "file": "lesson-voice/add-2d-noregroup/ramlah/written.mp3",
        "durationInSeconds": 5.805
      }
    ]
  },
  "add-2d-regroup": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-2d-regroup/ramlah/ask.mp3",
        "durationInSeconds": 3.297
      },
      {
        "id": "build",
        "file": "lesson-voice/add-2d-regroup/ramlah/build.mp3",
        "durationInSeconds": 4.83
      },
      {
        "id": "regroup",
        "file": "lesson-voice/add-2d-regroup/ramlah/regroup.mp3",
        "durationInSeconds": 19.18
      },
      {
        "id": "written",
        "file": "lesson-voice/add-2d-regroup/ramlah/written.mp3",
        "durationInSeconds": 6.873
      }
    ]
  },
  "sub-2d-noborrow": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/ask.mp3",
        "durationInSeconds": 3.762
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/build.mp3",
        "durationInSeconds": 3.855
      },
      {
        "id": "regroup",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/regroup.mp3",
        "durationInSeconds": 7.616
      },
      {
        "id": "written",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/written.mp3",
        "durationInSeconds": 6.409
      }
    ]
  },
  "sub-2d-borrow": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-2d-borrow/ramlah/ask.mp3",
        "durationInSeconds": 3.529
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-2d-borrow/ramlah/build.mp3",
        "durationInSeconds": 4.04
      },
      {
        "id": "regroup",
        "file": "lesson-voice/sub-2d-borrow/ramlah/regroup.mp3",
        "durationInSeconds": 13.932
      },
      {
        "id": "written",
        "file": "lesson-voice/sub-2d-borrow/ramlah/written.mp3",
        "durationInSeconds": 6.827
      }
    ]
  },
  "add-doubles": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-doubles/ramlah/ask.mp3",
        "durationInSeconds": 2.554
      },
      {
        "id": "build",
        "file": "lesson-voice/add-doubles/ramlah/build.mp3",
        "durationInSeconds": 3.901
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-doubles/ramlah/strategy.mp3",
        "durationInSeconds": 9.474
      },
      {
        "id": "record",
        "file": "lesson-voice/add-doubles/ramlah/record.mp3",
        "durationInSeconds": 3.622
      }
    ]
  },
  "add-make-ten": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-make-ten/ramlah/ask.mp3",
        "durationInSeconds": 2.322
      },
      {
        "id": "build",
        "file": "lesson-voice/add-make-ten/ramlah/build.mp3",
        "durationInSeconds": 3.808
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-make-ten/ramlah/strategy.mp3",
        "durationInSeconds": 8.452
      },
      {
        "id": "record",
        "file": "lesson-voice/add-make-ten/ramlah/record.mp3",
        "durationInSeconds": 3.901
      }
    ]
  },
  "sub-bridge": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-bridge/ramlah/ask.mp3",
        "durationInSeconds": 2.926
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-bridge/ramlah/build.mp3",
        "durationInSeconds": 2.647
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-bridge/ramlah/strategy.mp3",
        "durationInSeconds": 7.291
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-bridge/ramlah/record.mp3",
        "durationInSeconds": 4.737
      }
    ]
  },
  "add-count-on": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-count-on/ramlah/ask.mp3",
        "durationInSeconds": 2.415
      },
      {
        "id": "build",
        "file": "lesson-voice/add-count-on/ramlah/build.mp3",
        "durationInSeconds": 4.18
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-count-on/ramlah/strategy.mp3",
        "durationInSeconds": 2.879
      },
      {
        "id": "record",
        "file": "lesson-voice/add-count-on/ramlah/record.mp3",
        "durationInSeconds": 4.087
      }
    ]
  },
  "add-zero-comm": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-zero-comm/ramlah/ask.mp3",
        "durationInSeconds": 2.276
      },
      {
        "id": "build",
        "file": "lesson-voice/add-zero-comm/ramlah/build.mp3",
        "durationInSeconds": 4.319
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-zero-comm/ramlah/strategy.mp3",
        "durationInSeconds": 9.845
      },
      {
        "id": "record",
        "file": "lesson-voice/add-zero-comm/ramlah/record.mp3",
        "durationInSeconds": 5.526
      }
    ]
  },
  "add-near-doubles": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-near-doubles/ramlah/ask.mp3",
        "durationInSeconds": 2.508
      },
      {
        "id": "build",
        "file": "lesson-voice/add-near-doubles/ramlah/build.mp3",
        "durationInSeconds": 3.808
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-near-doubles/ramlah/strategy.mp3",
        "durationInSeconds": 7.43
      },
      {
        "id": "record",
        "file": "lesson-voice/add-near-doubles/ramlah/record.mp3",
        "durationInSeconds": 4.876
      }
    ]
  },
  "sub-count-back": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-count-back/ramlah/ask.mp3",
        "durationInSeconds": 2.879
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-count-back/ramlah/build.mp3",
        "durationInSeconds": 2.694
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-count-back/ramlah/strategy.mp3",
        "durationInSeconds": 2.833
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-count-back/ramlah/record.mp3",
        "durationInSeconds": 4.272
      }
    ]
  },
  "sub-zero": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-zero/ramlah/ask.mp3",
        "durationInSeconds": 2.694
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-zero/ramlah/build.mp3",
        "durationInSeconds": 2.368
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-zero/ramlah/strategy.mp3",
        "durationInSeconds": 3.947
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-zero/ramlah/record.mp3",
        "durationInSeconds": 4.272
      }
    ]
  },
  "sub-halves": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-halves/ramlah/ask.mp3",
        "durationInSeconds": 2.926
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-halves/ramlah/build.mp3",
        "durationInSeconds": 2.786
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-halves/ramlah/strategy.mp3",
        "durationInSeconds": 6.409
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-halves/ramlah/record.mp3",
        "durationInSeconds": 5.526
      }
    ]
  },
  "mul-identity": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-identity/ramlah/ask.mp3",
        "durationInSeconds": 3.111
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-identity/ramlah/groups.mp3",
        "durationInSeconds": 5.666
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-identity/ramlah/count.mp3",
        "durationInSeconds": 9.009
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-identity/ramlah/trick.mp3",
        "durationInSeconds": 11.981
      }
    ]
  },
  "mul-squares": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-squares/ramlah/ask.mp3",
        "durationInSeconds": 2.972
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-squares/ramlah/groups.mp3",
        "durationInSeconds": 6.037
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-squares/ramlah/count.mp3",
        "durationInSeconds": 11.796
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-squares/ramlah/trick.mp3",
        "durationInSeconds": 6.455
      }
    ]
  },
  "mul-6-9": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-6-9/ramlah/ask.mp3",
        "durationInSeconds": 3.019
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-6-9/ramlah/groups.mp3",
        "durationInSeconds": 6.223
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-6-9/ramlah/count.mp3",
        "durationInSeconds": 11.146
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-6-9/ramlah/trick.mp3",
        "durationInSeconds": 9.474
      }
    ]
  },
  "mul-10-12": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-10-12/ramlah/ask.mp3",
        "durationInSeconds": 2.368
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-10-12/ramlah/groups.mp3",
        "durationInSeconds": 5.759
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-10-12/ramlah/count.mp3",
        "durationInSeconds": 11.146
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-10-12/ramlah/trick.mp3",
        "durationInSeconds": 5.759
      }
    ]
  },
  "div-skip": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-skip/ramlah/ask.mp3",
        "durationInSeconds": 5.526
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-skip/ramlah/deal.mp3",
        "durationInSeconds": 9.706
      },
      {
        "id": "group",
        "file": "lesson-voice/div-skip/ramlah/group.mp3",
        "durationInSeconds": 11.749
      },
      {
        "id": "record",
        "file": "lesson-voice/div-skip/ramlah/record.mp3",
        "durationInSeconds": 4.876
      }
    ]
  },
  "div-identity": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-identity/ramlah/ask.mp3",
        "durationInSeconds": 5.526
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-identity/ramlah/deal.mp3",
        "durationInSeconds": 9.195
      },
      {
        "id": "group",
        "file": "lesson-voice/div-identity/ramlah/group.mp3",
        "durationInSeconds": 12.399
      },
      {
        "id": "record",
        "file": "lesson-voice/div-identity/ramlah/record.mp3",
        "durationInSeconds": 3.483
      }
    ]
  },
  "div-squares": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-squares/ramlah/ask.mp3",
        "durationInSeconds": 6.409
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-squares/ramlah/deal.mp3",
        "durationInSeconds": 8.731
      },
      {
        "id": "group",
        "file": "lesson-voice/div-squares/ramlah/group.mp3",
        "durationInSeconds": 11.378
      },
      {
        "id": "record",
        "file": "lesson-voice/div-squares/ramlah/record.mp3",
        "durationInSeconds": 5.759
      }
    ]
  },
  "div-3-4": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-3-4/ramlah/ask.mp3",
        "durationInSeconds": 5.666
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-3-4/ramlah/deal.mp3",
        "durationInSeconds": 7.941
      },
      {
        "id": "group",
        "file": "lesson-voice/div-3-4/ramlah/group.mp3",
        "durationInSeconds": 12.817
      },
      {
        "id": "record",
        "file": "lesson-voice/div-3-4/ramlah/record.mp3",
        "durationInSeconds": 5.851
      }
    ]
  },
  "div-6-9": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-6-9/ramlah/ask.mp3",
        "durationInSeconds": 5.851
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-6-9/ramlah/deal.mp3",
        "durationInSeconds": 9.242
      },
      {
        "id": "group",
        "file": "lesson-voice/div-6-9/ramlah/group.mp3",
        "durationInSeconds": 12.539
      },
      {
        "id": "record",
        "file": "lesson-voice/div-6-9/ramlah/record.mp3",
        "durationInSeconds": 5.294
      }
    ]
  },
  "div-10-12": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-10-12/ramlah/ask.mp3",
        "durationInSeconds": 5.991
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-10-12/ramlah/deal.mp3",
        "durationInSeconds": 9.892
      },
      {
        "id": "group",
        "file": "lesson-voice/div-10-12/ramlah/group.mp3",
        "durationInSeconds": 12.91
      },
      {
        "id": "record",
        "file": "lesson-voice/div-10-12/ramlah/record.mp3",
        "durationInSeconds": 5.619
      }
    ]
  },
  "div-remainder": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-remainder/ramlah/ask.mp3",
        "durationInSeconds": 5.759
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-remainder/ramlah/deal.mp3",
        "durationInSeconds": 16.3
      },
      {
        "id": "group",
        "file": "lesson-voice/div-remainder/ramlah/group.mp3",
        "durationInSeconds": 16.254
      },
      {
        "id": "record",
        "file": "lesson-voice/div-remainder/ramlah/record.mp3",
        "durationInSeconds": 7.105
      }
    ]
  }
};
