// src/remotion/lesson/voice-manifest.ts
// GENERATED by scripts/build-lesson-voice.ts — do not hand-edit.
export interface VoiceClip {
  id: string;
  file: string; // relative to public/
  durationInSeconds: number;
}

/** unit id → voice key → that voice's clips for the unit. */
export const CLIPS_BY_UNIT: Record<string, Record<string, VoiceClip[]>> = {
  "mul-skip": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-skip/ramlah/ask.mp3",
        "durationInSeconds": 2.926
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-skip/ramlah/groups.mp3",
        "durationInSeconds": 6.177
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-skip/ramlah/count.mp3",
        "durationInSeconds": 13.003
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-skip/ramlah/trick.mp3",
        "durationInSeconds": 5.805
      }
    ]
  },
  "mul-3-4": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-3-4/ramlah/ask.mp3",
        "durationInSeconds": 2.694
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-3-4/ramlah/groups.mp3",
        "durationInSeconds": 5.573
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-3-4/ramlah/count.mp3",
        "durationInSeconds": 12.91
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-3-4/ramlah/trick.mp3",
        "durationInSeconds": 6.966
      }
    ]
  },
  "mul-tens": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-tens/ramlah/ask.mp3",
        "durationInSeconds": 2.879
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-tens/ramlah/groups.mp3",
        "durationInSeconds": 5.851
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-tens/ramlah/count.mp3",
        "durationInSeconds": 9.288
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-tens/ramlah/trick.mp3",
        "durationInSeconds": 8.777
      }
    ]
  },
  "add-2d-noregroup": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-2d-noregroup/ramlah/ask.mp3",
        "durationInSeconds": 3.019
      },
      {
        "id": "build",
        "file": "lesson-voice/add-2d-noregroup/ramlah/build.mp3",
        "durationInSeconds": 4.551
      },
      {
        "id": "regroup",
        "file": "lesson-voice/add-2d-noregroup/ramlah/regroup.mp3",
        "durationInSeconds": 8.545
      },
      {
        "id": "written",
        "file": "lesson-voice/add-2d-noregroup/ramlah/written.mp3",
        "durationInSeconds": 6.037
      }
    ]
  },
  "add-2d-regroup": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-2d-regroup/ramlah/ask.mp3",
        "durationInSeconds": 3.297
      },
      {
        "id": "build",
        "file": "lesson-voice/add-2d-regroup/ramlah/build.mp3",
        "durationInSeconds": 4.272
      },
      {
        "id": "regroup",
        "file": "lesson-voice/add-2d-regroup/ramlah/regroup.mp3",
        "durationInSeconds": 19.273
      },
      {
        "id": "written",
        "file": "lesson-voice/add-2d-regroup/ramlah/written.mp3",
        "durationInSeconds": 7.291
      }
    ]
  },
  "sub-2d-noborrow": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/ask.mp3",
        "durationInSeconds": 3.39
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/build.mp3",
        "durationInSeconds": 3.947
      },
      {
        "id": "regroup",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/regroup.mp3",
        "durationInSeconds": 6.873
      },
      {
        "id": "written",
        "file": "lesson-voice/sub-2d-noborrow/ramlah/written.mp3",
        "durationInSeconds": 6.641
      }
    ]
  },
  "sub-2d-borrow": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-2d-borrow/ramlah/ask.mp3",
        "durationInSeconds": 3.483
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-2d-borrow/ramlah/build.mp3",
        "durationInSeconds": 3.994
      },
      {
        "id": "regroup",
        "file": "lesson-voice/sub-2d-borrow/ramlah/regroup.mp3",
        "durationInSeconds": 15
      },
      {
        "id": "written",
        "file": "lesson-voice/sub-2d-borrow/ramlah/written.mp3",
        "durationInSeconds": 6.873
      }
    ]
  },
  "add-doubles": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-doubles/ramlah/ask.mp3",
        "durationInSeconds": 2.694
      },
      {
        "id": "build",
        "file": "lesson-voice/add-doubles/ramlah/build.mp3",
        "durationInSeconds": 4.551
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-doubles/ramlah/strategy.mp3",
        "durationInSeconds": 8.916
      },
      {
        "id": "record",
        "file": "lesson-voice/add-doubles/ramlah/record.mp3",
        "durationInSeconds": 3.762
      }
    ]
  },
  "add-make-ten": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-make-ten/ramlah/ask.mp3",
        "durationInSeconds": 2.368
      },
      {
        "id": "build",
        "file": "lesson-voice/add-make-ten/ramlah/build.mp3",
        "durationInSeconds": 3.855
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-make-ten/ramlah/strategy.mp3",
        "durationInSeconds": 7.57
      },
      {
        "id": "record",
        "file": "lesson-voice/add-make-ten/ramlah/record.mp3",
        "durationInSeconds": 3.947
      }
    ]
  },
  "sub-bridge": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-bridge/ramlah/ask.mp3",
        "durationInSeconds": 2.786
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-bridge/ramlah/build.mp3",
        "durationInSeconds": 3.019
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-bridge/ramlah/strategy.mp3",
        "durationInSeconds": 7.152
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-bridge/ramlah/record.mp3",
        "durationInSeconds": 4.644
      }
    ]
  },
  "add-count-on": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-count-on/ramlah/ask.mp3",
        "durationInSeconds": 2.415
      },
      {
        "id": "build",
        "file": "lesson-voice/add-count-on/ramlah/build.mp3",
        "durationInSeconds": 4.598
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-count-on/ramlah/strategy.mp3",
        "durationInSeconds": 2.972
      },
      {
        "id": "record",
        "file": "lesson-voice/add-count-on/ramlah/record.mp3",
        "durationInSeconds": 3.808
      }
    ]
  },
  "add-zero-comm": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-zero-comm/ramlah/ask.mp3",
        "durationInSeconds": 2.601
      },
      {
        "id": "build",
        "file": "lesson-voice/add-zero-comm/ramlah/build.mp3",
        "durationInSeconds": 4.133
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-zero-comm/ramlah/strategy.mp3",
        "durationInSeconds": 9.288
      },
      {
        "id": "record",
        "file": "lesson-voice/add-zero-comm/ramlah/record.mp3",
        "durationInSeconds": 4.969
      }
    ]
  },
  "add-near-doubles": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/add-near-doubles/ramlah/ask.mp3",
        "durationInSeconds": 2.601
      },
      {
        "id": "build",
        "file": "lesson-voice/add-near-doubles/ramlah/build.mp3",
        "durationInSeconds": 4.551
      },
      {
        "id": "strategy",
        "file": "lesson-voice/add-near-doubles/ramlah/strategy.mp3",
        "durationInSeconds": 9.149
      },
      {
        "id": "record",
        "file": "lesson-voice/add-near-doubles/ramlah/record.mp3",
        "durationInSeconds": 4.226
      }
    ]
  },
  "sub-count-back": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-count-back/ramlah/ask.mp3",
        "durationInSeconds": 2.786
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-count-back/ramlah/build.mp3",
        "durationInSeconds": 2.136
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-count-back/ramlah/strategy.mp3",
        "durationInSeconds": 2.926
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-count-back/ramlah/record.mp3",
        "durationInSeconds": 4.087
      }
    ]
  },
  "sub-zero": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-zero/ramlah/ask.mp3",
        "durationInSeconds": 2.833
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-zero/ramlah/build.mp3",
        "durationInSeconds": 2.461
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-zero/ramlah/strategy.mp3",
        "durationInSeconds": 4.087
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-zero/ramlah/record.mp3",
        "durationInSeconds": 4.319
      }
    ]
  },
  "sub-halves": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/sub-halves/ramlah/ask.mp3",
        "durationInSeconds": 2.601
      },
      {
        "id": "build",
        "file": "lesson-voice/sub-halves/ramlah/build.mp3",
        "durationInSeconds": 2.461
      },
      {
        "id": "strategy",
        "file": "lesson-voice/sub-halves/ramlah/strategy.mp3",
        "durationInSeconds": 7.338
      },
      {
        "id": "record",
        "file": "lesson-voice/sub-halves/ramlah/record.mp3",
        "durationInSeconds": 5.526
      }
    ]
  },
  "mul-identity": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-identity/ramlah/ask.mp3",
        "durationInSeconds": 3.111
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-identity/ramlah/groups.mp3",
        "durationInSeconds": 5.944
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-identity/ramlah/count.mp3",
        "durationInSeconds": 10.495
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-identity/ramlah/trick.mp3",
        "durationInSeconds": 11.981
      }
    ]
  },
  "mul-squares": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-squares/ramlah/ask.mp3",
        "durationInSeconds": 2.833
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-squares/ramlah/groups.mp3",
        "durationInSeconds": 5.759
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-squares/ramlah/count.mp3",
        "durationInSeconds": 13.189
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-squares/ramlah/trick.mp3",
        "durationInSeconds": 6.548
      }
    ]
  },
  "mul-6-9": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-6-9/ramlah/ask.mp3",
        "durationInSeconds": 2.833
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-6-9/ramlah/groups.mp3",
        "durationInSeconds": 5.619
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-6-9/ramlah/count.mp3",
        "durationInSeconds": 10.635
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-6-9/ramlah/trick.mp3",
        "durationInSeconds": 8.545
      }
    ]
  },
  "mul-10-12": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/mul-10-12/ramlah/ask.mp3",
        "durationInSeconds": 2.786
      },
      {
        "id": "groups",
        "file": "lesson-voice/mul-10-12/ramlah/groups.mp3",
        "durationInSeconds": 5.666
      },
      {
        "id": "count",
        "file": "lesson-voice/mul-10-12/ramlah/count.mp3",
        "durationInSeconds": 10.867
      },
      {
        "id": "trick",
        "file": "lesson-voice/mul-10-12/ramlah/trick.mp3",
        "durationInSeconds": 5.991
      }
    ]
  },
  "div-skip": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-skip/ramlah/ask.mp3",
        "durationInSeconds": 5.759
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-skip/ramlah/deal.mp3",
        "durationInSeconds": 8.591
      },
      {
        "id": "group",
        "file": "lesson-voice/div-skip/ramlah/group.mp3",
        "durationInSeconds": 12.26
      },
      {
        "id": "record",
        "file": "lesson-voice/div-skip/ramlah/record.mp3",
        "durationInSeconds": 6.455
      }
    ]
  },
  "div-identity": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-identity/ramlah/ask.mp3",
        "durationInSeconds": 5.712
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-identity/ramlah/deal.mp3",
        "durationInSeconds": 8.963
      },
      {
        "id": "group",
        "file": "lesson-voice/div-identity/ramlah/group.mp3",
        "durationInSeconds": 12.353
      },
      {
        "id": "record",
        "file": "lesson-voice/div-identity/ramlah/record.mp3",
        "durationInSeconds": 4.133
      }
    ]
  },
  "div-squares": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-squares/ramlah/ask.mp3",
        "durationInSeconds": 5.526
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-squares/ramlah/deal.mp3",
        "durationInSeconds": 7.663
      },
      {
        "id": "group",
        "file": "lesson-voice/div-squares/ramlah/group.mp3",
        "durationInSeconds": 12.399
      },
      {
        "id": "record",
        "file": "lesson-voice/div-squares/ramlah/record.mp3",
        "durationInSeconds": 7.338
      }
    ]
  },
  "div-3-4": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-3-4/ramlah/ask.mp3",
        "durationInSeconds": 6.223
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-3-4/ramlah/deal.mp3",
        "durationInSeconds": 9.242
      },
      {
        "id": "group",
        "file": "lesson-voice/div-3-4/ramlah/group.mp3",
        "durationInSeconds": 12.725
      },
      {
        "id": "record",
        "file": "lesson-voice/div-3-4/ramlah/record.mp3",
        "durationInSeconds": 6.966
      }
    ]
  },
  "div-6-9": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-6-9/ramlah/ask.mp3",
        "durationInSeconds": 5.991
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-6-9/ramlah/deal.mp3",
        "durationInSeconds": 8.963
      },
      {
        "id": "group",
        "file": "lesson-voice/div-6-9/ramlah/group.mp3",
        "durationInSeconds": 11.703
      },
      {
        "id": "record",
        "file": "lesson-voice/div-6-9/ramlah/record.mp3",
        "durationInSeconds": 7.616
      }
    ]
  },
  "div-10-12": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-10-12/ramlah/ask.mp3",
        "durationInSeconds": 5.991
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-10-12/ramlah/deal.mp3",
        "durationInSeconds": 10.031
      },
      {
        "id": "group",
        "file": "lesson-voice/div-10-12/ramlah/group.mp3",
        "durationInSeconds": 11.889
      },
      {
        "id": "record",
        "file": "lesson-voice/div-10-12/ramlah/record.mp3",
        "durationInSeconds": 7.105
      }
    ]
  },
  "div-remainder": {
    "ramlah": [
      {
        "id": "ask",
        "file": "lesson-voice/div-remainder/ramlah/ask.mp3",
        "durationInSeconds": 5.666
      },
      {
        "id": "deal",
        "file": "lesson-voice/div-remainder/ramlah/deal.mp3",
        "durationInSeconds": 14.165
      },
      {
        "id": "group",
        "file": "lesson-voice/div-remainder/ramlah/group.mp3",
        "durationInSeconds": 14.304
      },
      {
        "id": "record",
        "file": "lesson-voice/div-remainder/ramlah/record.mp3",
        "durationInSeconds": 6.177
      }
    ]
  }
};
