// src/remotion/lesson/voice-manifest.ts
// GENERATED by scripts/build-lesson-voice.mjs — do not hand-edit.
//
// Empty by default, which is what keeps the video renderable with no audio at
// all. Once the mp3s exist under public/lesson-voice/, this lists them with
// their real durations and the timeline stretches each scene to fit its line.
export interface VoiceClip {
  id: string;
  file: string; // relative to public/
  durationInSeconds: number;
}

export const VOICE_CLIPS: VoiceClip[] = [];
