// src/app/about/page.tsx
import Link from "next/link";

export const metadata = {
  title: "About Eduyro — Why We Built a Kumon-Style Program for Home Printing",
  description:
    "Eduyro is a print-first, mastery-based learning program for Pre-K to Grade 12 — built so every family can afford the kind of daily, structured practice that builds real fluency.",
  alternates: { canonical: "/about" },
};

export default function AboutPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <div className="mb-8">
        <Link href="/" className="text-sm text-muted hover:text-ink transition-colors">
          ← Back to home
        </Link>
      </div>

      <h1 className="font-serif text-4xl font-bold mb-2">About Eduyro</h1>
      <p className="text-sm text-muted mb-10">Mastery learning, one worksheet at a time.</p>

      <div className="space-y-8 text-ink">
        <section>
          <h2 className="font-serif text-xl font-bold mb-3">Why Eduyro exists</h2>
          <p className="text-sm leading-relaxed text-muted mb-3">
            Programs like Kumon work because of one simple idea: a little structured practice every
            day, at exactly the right level, beats occasional cramming every time. The problem is the
            price — $150–200 per month, per child, puts that kind of practice out of reach for most
            families.
          </p>
          <p className="text-sm leading-relaxed text-muted">
            Eduyro brings the same method — daily worksheets, careful progression, mastery before
            advancement — to any family with a printer, at a fraction of the cost.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold mb-3">How our curriculum works</h2>
          <p className="text-sm leading-relaxed text-muted mb-3">
            Every worksheet is generated by a curriculum engine that guarantees what a good tutor
            would: no two identical questions on a sheet, difficulty that rises from the first
            problem to the last, and a progression across sheets where each one is measurably harder
            than the one before. A free placement test finds each child&rsquo;s exact starting level,
            and students advance only when they demonstrate mastery.
          </p>
          <p className="text-sm leading-relaxed text-muted">
            The curriculum spans Pre-K to Grade 12 — from early counting through fractions, decimals,
            pre-algebra, linear equations, and polynomials — plus Reading, Writing, and Science
            practice.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold mb-3">Print-first, on purpose</h2>
          <p className="text-sm leading-relaxed text-muted">
            Screens are great for many things, but pencil-and-paper practice builds focus,
            handwriting, and working memory in a way tapping answers doesn&rsquo;t. Eduyro is designed
            to be printed: clean black-and-white worksheets, answer keys for fast parent grading, and
            daily packets that take 10–20 minutes.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl font-bold mb-3">Get in touch</h2>
          <p className="text-sm leading-relaxed text-muted">
            Questions, feedback, or school inquiries — email us at{" "}
            <a href="mailto:support@eduyro.com" className="text-brand-blue hover:underline">
              support@eduyro.com
            </a>
            . We read everything.
          </p>
        </section>
      </div>
    </main>
  );
}
