// src/lib/tutorials/concepts-nonmath.ts
// Per-SKILL pre-practice lessons for Reading / Writing / Science. Math has
// bespoke animated concepts (see concepts.ts); these subjects get a narrated,
// text-forward lesson + key insights + a simple per-subject illustration, shown
// once before a student's first practice of each skill (the norm: learn, then do).

import type { ConceptTutorial } from "./concepts";

type Spec = { title: string; narration: string; bullets: string[] };

const VISUAL: Record<string, string> = { R: "readingLesson", W: "writingLesson", S: "scienceLesson" };

// ── READING ───────────────────────────────────────────────────────────────────
const READING: Record<string, Spec> = {
  "uppercase letters": { title: "Uppercase letters", narration: "Capital letters are the big, tall letters. We use them to start a sentence and for names. Let's learn to spot the big A, B, C from their little partners.", bullets: ["Uppercase = the BIG letters (A, B, C)", "Every name and sentence starts with one", "Look for the taller, fuller shape"] },
  "lowercase letters": { title: "Lowercase letters", narration: "Lowercase letters are the small, everyday letters we use most. Some are short like 'a', some have tails like 'g'. Let's learn to match each one to its capital.", bullets: ["Lowercase = the small letters (a, b, c)", "Most of the words you read are lowercase", "Each lowercase has a capital partner"] },
  "letter sounds": { title: "Letter sounds", narration: "Every letter makes a sound. 'M' says mmm, 'S' says sss. When you know the sound each letter makes, you can start to read words. Listen for the first sound in a word.", bullets: ["Each letter has its own sound", "'M' says /m/, 'S' says /s/", "Blend sounds together to read a word"] },

  "silent e words": { title: "Silent E", narration: "Here's a magic trick: a silent E at the end of a word makes the vowel say its own name. 'cap' becomes 'cape', 'kit' becomes 'kite'. The E is silent but it's powerful.", bullets: ["Silent E makes the vowel say its name", "cap → cape, kit → kite, hop → hope", "You don't say the E out loud"] },
  "long a sound": { title: "Long A", narration: "The long A says its name — 'aaay'. You'll find it in cake, rain, and play. Watch for the patterns a_e, ai, and ay.", bullets: ["Long A says its name, like in 'cake'", "Spellings: a_e (cake), ai (rain), ay (play)", "Short A is different: 'cat'"] },
  "long i sound": { title: "Long I", narration: "The long I says its name — 'iii'. Listen for it in kite, night, and fly. Look for i_e, igh, and y.", bullets: ["Long I says its name, like in 'kite'", "Spellings: i_e (kite), igh (night), y (fly)", "Short I is different: 'sit'"] },
  "long o sound": { title: "Long O", narration: "The long O says its name — 'ooo'. Hear it in boat, home, and snow. Watch for o_e, oa, and ow.", bullets: ["Long O says its name, like in 'home'", "Spellings: o_e (home), oa (boat), ow (snow)", "Short O is different: 'hot'"] },

  "dolch list 1–50": { title: "Sight words (Dolch 1–50)", narration: "Sight words are the words you see everywhere — the, and, is, you. They pop up so often that we learn to read them in a flash, without sounding them out.", bullets: ["Sight words appear over and over", "Read them instantly, don't sound them out", "Knowing them makes reading faster"] },
  "dolch list 51–100": { title: "Sight words (Dolch 51–100)", narration: "More everyday words to know by sight — like 'because', 'were', and 'their'. The more you recognize instantly, the smoother your reading becomes.", bullets: ["A second set of must-know words", "Recognize each one at a glance", "Practice until they feel automatic"] },
  "fry words 1–100": { title: "Sight words (Fry 1–100)", narration: "The Fry words are the most common words in everything we read. Master these and you'll already know a huge chunk of any page.", bullets: ["The most frequent words in English", "Know them on sight, no sounding out", "They unlock faster, easier reading"] },

  "context clues": { title: "Context clues", narration: "When you meet a word you don't know, don't stop — be a detective. The words around it give you clues to its meaning. Read the whole sentence and make your best guess.", bullets: ["Use nearby words to figure out a new word", "Read the whole sentence for clues", "Guess the meaning, then check if it fits"] },
  "synonyms": { title: "Synonyms", narration: "Synonyms are words that mean the same thing — happy and glad, big and large. Knowing synonyms makes your reading and writing richer.", bullets: ["Synonyms mean the SAME (happy = glad)", "They help you avoid repeating words", "Pick the one that fits best"] },
  "antonyms": { title: "Antonyms", narration: "Antonyms are opposites — hot and cold, up and down. Spotting opposites helps you understand exactly what a writer means.", bullets: ["Antonyms are OPPOSITES (hot ↔ cold)", "Opposites sharpen meaning", "Watch for words like 'not' and 'un-'"] },

  "main idea & details": { title: "Main idea & details", narration: "Every passage has one big point — the main idea — and smaller facts that support it, the details. Ask yourself: what is this mostly about?", bullets: ["Main idea = what it's MOSTLY about", "Details are the small facts that back it up", "Ask 'what's the big point?'"] },
  "cause and effect": { title: "Cause and effect", narration: "A cause is why something happens; the effect is what happens. It rained (cause), so the game was cancelled (effect). Look for 'because', 'so', and 'as a result'.", bullets: ["Cause = why; Effect = what happened", "Signal words: because, so, as a result", "One cause can lead to many effects"] },
  "sequence of events": { title: "Sequence of events", narration: "Stories and steps happen in order. Signal words like first, next, then, and finally tell you the sequence. Putting events in order helps you follow along.", bullets: ["Sequence = the order things happen", "Signal words: first, next, then, finally", "Re-tell it in order to check"] },
  "making inferences": { title: "Making inferences", narration: "Sometimes a writer doesn't tell you everything — you infer. You combine the clues in the text with what you already know to figure out what's really going on.", bullets: ["Infer = clues in the text + what you know", "The answer isn't stated directly", "Back up your inference with evidence"] },

  "drawing conclusions": { title: "Drawing conclusions", narration: "Drawing a conclusion is using the clues to decide what must be true. Muddy boots and a wet coat? You can conclude it was raining. Use the evidence.", bullets: ["Use clues to decide what's true", "Base it on evidence, not a wild guess", "Ask: what do all the clues point to?"] },
  "predicting outcomes": { title: "Predicting outcomes", narration: "A prediction is a smart guess about what happens next, using clues from the text and what usually happens. Dark clouds rolling in? You can predict rain.", bullets: ["Predict = a clue-based guess at what's next", "Use details + what usually happens", "Keep reading to check your prediction"] },

  "identify author's purpose": { title: "Author's purpose", narration: "Every writer has a reason: to persuade, to inform, or to entertain — remember PIE. Ask what the author wants you to think, learn, or feel.", bullets: ["Purpose: Persuade, Inform, Entertain (PIE)", "Ask what the author wants from you", "Look at the kind of writing it is"] },
  "tone and mood": { title: "Tone and mood", narration: "Tone is how the author feels about the topic; mood is how the writing makes YOU feel. Word choices — gloomy, cheerful, tense — create both.", bullets: ["Tone = the author's attitude", "Mood = the feeling YOU get", "Word choice creates both"] },
  "fact vs. opinion": { title: "Fact vs. opinion", narration: "A fact can be proven true; an opinion is what someone believes. 'Water freezes at 0°C' is a fact. 'Winter is the best season' is an opinion. Watch for words like best and should.", bullets: ["Fact = can be proven true", "Opinion = a personal belief", "Opinion words: best, worst, should"] },
  "point of view": { title: "Point of view", narration: "Point of view is who is telling the story. First person uses 'I'; third person uses 'he, she, they'. Knowing the narrator shapes what you learn.", bullets: ["First person uses 'I, me, we'", "Third person uses 'he, she, they'", "The narrator shapes what you know"] },

  "similes and metaphors": { title: "Similes & metaphors", narration: "Both compare two things. A simile uses 'like' or 'as' — 'brave as a lion'. A metaphor says one thing IS another — 'the classroom was a zoo'.", bullets: ["Simile compares using 'like' or 'as'", "Metaphor says one thing IS another", "Both paint a vivid picture"] },
  "personification": { title: "Personification", narration: "Personification gives human actions to things that aren't human. 'The wind whispered' — wind can't really whisper, but it helps you feel the scene.", bullets: ["Gives human traits to non-human things", "'The wind whispered', 'the sun smiled'", "Makes writing come alive"] },
  "hyperbole": { title: "Hyperbole", narration: "Hyperbole is huge exaggeration you're not meant to take literally. 'I've told you a million times!' No one means exactly a million — it's for effect.", bullets: ["Hyperbole = extreme exaggeration", "Not meant literally", "Used for emphasis or humor"] },
  "idioms": { title: "Idioms", narration: "An idiom is a phrase whose real meaning is different from the words. 'It's raining cats and dogs' means it's raining hard — not actual animals!", bullets: ["Meaning ≠ the literal words", "'Break a leg' = good luck", "Learn them as whole phrases"] },

  "character analysis": { title: "Character analysis", narration: "To understand a character, watch what they say, do, and think. Their actions reveal their traits — brave, kind, selfish. Notice how they change.", bullets: ["Judge characters by words + actions", "Look for traits and motivations", "Notice if they change (dynamic) or not"] },
  "theme identification": { title: "Theme", narration: "The theme is the big lesson or message of a story — like 'kindness matters' or 'never give up'. It's bigger than the plot; it's what the story teaches.", bullets: ["Theme = the story's deeper message", "It's the lesson, not the plot", "Ask: what is this really about?"] },
  "figurative language": { title: "Figurative language", narration: "Figurative language means words that paint pictures instead of saying things plainly — similes, metaphors, personification, idioms. Writers use it to make you feel and see.", bullets: ["Language that paints a picture", "Includes similes, metaphors, idioms", "Look for meaning beyond the literal"] },
  "narrative structure": { title: "Narrative structure", narration: "Most stories follow a shape: exposition, rising action, climax, falling action, resolution. Knowing the shape helps you see where the story is going.", bullets: ["Beginning, middle, turning point, end", "Climax = the most intense moment", "Conflict drives the story forward"] },
};

// ── WRITING ─────────────────────────────────────────────────────────────────
const WRITING: Record<string, Spec> = {
  "completing sentences": { title: "Complete sentences", narration: "A complete sentence tells a whole thought — it has a who/what and what they do. It starts with a capital and ends with a mark. Let's finish sentences so they make sense.", bullets: ["A sentence = one whole thought", "Starts with a capital, ends with . ? !", "Has a naming part and a doing part"] },
  "capital letters": { title: "Capital letters", narration: "We capitalize the first letter of every sentence and every name — like Sam, Monday, or London. Capitals tell the reader something important is starting.", bullets: ["Start every sentence with a capital", "Names always get a capital", "'i' is always capital when it means me: I"] },
  "periods": { title: "Periods", narration: "A telling sentence ends with a period — a little dot that means 'stop here'. It helps the reader know where one idea ends and the next begins.", bullets: ["A period ends a telling sentence", "It means: full stop", "Questions use ?, excitement uses !"] },

  "nouns and verbs": { title: "Nouns & verbs", narration: "Nouns name people, places, and things — dog, school, Maria. Verbs are the action — run, eat, jump. Every sentence needs a noun and a verb.", bullets: ["Noun = person, place, or thing", "Verb = the action or 'being' word", "Find the noun and verb in every sentence"] },
  "adjectives and adverbs": { title: "Adjectives & adverbs", narration: "Adjectives describe nouns — a TALL tree, a RED car. Adverbs describe verbs, often ending in -ly — she ran QUICKLY. They add detail and color.", bullets: ["Adjectives describe nouns (tall, red)", "Adverbs describe verbs (quickly, softly)", "Many adverbs end in -ly"] },
  "pronouns": { title: "Pronouns", narration: "Pronouns stand in for nouns so we don't repeat names — he, she, it, they. 'Maria ran' becomes 'She ran'. They keep writing smooth.", bullets: ["Pronouns replace nouns (he, she, they)", "They avoid repeating the same name", "Make sure it's clear who 'they' means"] },
  "prepositions": { title: "Prepositions", narration: "Prepositions show position or direction — on, under, in, before. 'The cat sat UNDER the table.' They tell you where or when.", bullets: ["Show position/time (on, under, in)", "Start a phrase: 'under the table'", "Tell where or when"] },

  "subjects and predicates": { title: "Subjects & predicates", narration: "Every sentence has two parts: the subject (who or what it's about) and the predicate (what they do or are). 'The big dog | barked loudly.'", bullets: ["Subject = who/what the sentence is about", "Predicate = what they do or are", "Both are needed for a complete sentence"] },
  "simple sentences": { title: "Simple sentences", narration: "A simple sentence has one complete idea — one subject and one predicate. 'The dog barked.' Short, clear, and complete.", bullets: ["One complete idea", "One subject + one predicate", "Can stand on its own"] },
  "compound sentences": { title: "Compound sentences", narration: "A compound sentence joins two complete sentences with a connector like and, but, or so. 'I like tea, but she likes coffee.'", bullets: ["Two complete sentences joined", "Connectors: and, but, or, so", "Usually a comma before the connector"] },
  "complex sentences": { title: "Complex sentences", narration: "A complex sentence adds a dependent part that can't stand alone, often starting with because, when, or although. 'When the bell rang, we left.'", bullets: ["One main idea + a dependent part", "Dependent starters: because, when, although", "The dependent part can't stand alone"] },
  "run-ons and fragments": { title: "Run-ons & fragments", narration: "A fragment is missing a piece — it's not a whole thought. A run-on jams two sentences together with no punctuation. Let's fix both so each idea is clear.", bullets: ["Fragment = incomplete thought", "Run-on = two sentences smashed together", "Fix with a period or a comma + connector"] },

  "commas": { title: "Commas", narration: "Commas tell the reader to pause. We use them in lists — apples, oranges, and pears — and before a connector that joins two sentences.", bullets: ["Commas separate items in a list", "Use one before and/but joining sentences", "They tell the reader to pause"] },
  "apostrophes": { title: "Apostrophes", narration: "Apostrophes do two jobs: they show ownership — the dog's bone — and they squeeze words together in contractions — it's, don't.", bullets: ["Show ownership: the dog's bone", "Make contractions: it's, don't, can't", "It's = it is; its = belonging to it"] },
  "quotation marks": { title: "Quotation marks", narration: "Quotation marks wrap the exact words someone says. \"Let's go,\" said Mia. The end punctuation goes inside the quotes.", bullets: ["Wrap the exact spoken words", "End punctuation goes inside the quotes", "New speaker → new line"] },
  "semicolons": { title: "Semicolons", narration: "A semicolon links two closely related complete sentences without a connector. 'It rained all day; the game was cancelled.' It's stronger than a comma.", bullets: ["Joins two related complete sentences", "No 'and/but' needed", "Stronger than a comma, softer than a period"] },

  "topic sentences": { title: "Topic sentences", narration: "A topic sentence is the headline of a paragraph — it tells the one main idea. A strong one is clear and focused, not too broad or too tiny.", bullets: ["States the paragraph's main idea", "Usually comes first", "Clear and focused, not vague"] },
  "supporting sentences": { title: "Supporting sentences", narration: "Supporting sentences back up the topic sentence with details, facts, and examples. They answer 'how do you know?' and make your paragraph convincing.", bullets: ["Give details, facts, examples", "Each one supports the topic sentence", "Specifics beat vague statements"] },
  "concluding sentences": { title: "Concluding sentences", narration: "A concluding sentence wraps up a paragraph — it restates the main idea in fresh words without starting something new. It signals 'we're done here'.", bullets: ["Wraps up the paragraph", "Restates the main idea in new words", "Don't add a brand-new idea"] },
  "paragraph unity": { title: "Paragraph unity", narration: "A unified paragraph sticks to ONE main idea — every sentence belongs. If a sentence wanders off topic, take it out. Unity keeps writing clear.", bullets: ["Every sentence supports one idea", "Cut anything off-topic", "Unity = focus"] },

  "introductions": { title: "Introductions", narration: "An introduction hooks the reader, gives a little background, and ends with the thesis — your main point. It's the doorway into your essay.", bullets: ["Hook to grab attention", "Brief background", "End with a clear thesis"] },
  "body paragraphs": { title: "Body paragraphs", narration: "Each body paragraph develops ONE point that supports your thesis, with evidence and explanation. Transitions link them smoothly.", bullets: ["One main point per paragraph", "Back it with evidence + explanation", "Connect to the thesis"] },
  "conclusions": { title: "Conclusions", narration: "A conclusion restates your thesis, sums up your points, and leaves a final thought. Don't introduce new evidence — wrap it up well.", bullets: ["Restate the thesis in new words", "Sum up the main points", "End with a memorable thought"] },
  "transitions": { title: "Transitions", narration: "Transitions are bridges between ideas — however, therefore, for example, next. They guide the reader smoothly from one point to the next.", bullets: ["Bridge words between ideas", "Show contrast, cause, examples, order", "However, therefore, for example, next"] },

  "plot structure": { title: "Plot structure", narration: "A plot has a shape: exposition sets it up, rising action builds tension, the climax is the turning point, then falling action and resolution. Plan the shape before you write.", bullets: ["Exposition → rising action → climax", "Then falling action → resolution", "Conflict drives the plot"] },
  "character development": { title: "Character development", narration: "Bring characters to life by showing their traits through actions, words, and choices — not just telling us. Strong characters want something and change.", bullets: ["Show traits through actions and words", "Give characters a goal", "Let them grow or change"] },
  "setting and mood": { title: "Setting & mood", narration: "Setting is the time and place; mood is the feeling it creates. Sensory details — a cold wind, golden light — build both and pull readers in.", bullets: ["Setting = time + place", "Mood = the feeling it creates", "Use sensory details"] },
  "dialogue": { title: "Dialogue", narration: "Dialogue is characters speaking. Punctuate it correctly with quotation marks, start a new line for each speaker, and let it reveal personality.", bullets: ["Quotation marks around spoken words", "New speaker, new line", "Good dialogue reveals character"] },

  "claims and evidence": { title: "Claims & evidence", narration: "A claim is the position you argue. Strong evidence — facts, statistics, expert sources — proves it. Always explain how the evidence supports your claim.", bullets: ["Claim = your position", "Back it with specific, reliable evidence", "Explain how the evidence proves it"] },
  "counterarguments": { title: "Counterarguments", narration: "A counterargument is the other side's best point. Smart writers name it and then refute it — it shows you've thought it through and makes you more convincing.", bullets: ["The opposing side's strongest point", "Acknowledge it fairly", "Then refute it with reasons"] },
  "persuasive techniques": { title: "Persuasive techniques", narration: "Persuasion uses three appeals: ethos (credibility), pathos (emotion), and logos (logic). Mixing them makes your argument powerful.", bullets: ["Ethos = credibility", "Pathos = emotion", "Logos = logic and facts"] },
  "essay structure": { title: "Essay structure", narration: "A persuasive essay has an intro with a thesis, body paragraphs each making one reason with evidence, a counterargument, and a strong conclusion.", bullets: ["Intro + thesis → body reasons → conclusion", "One reason per body paragraph", "Address the other side"] },
};

// ── SCIENCE ─────────────────────────────────────────────────────────────────
const SCIENCE: Record<string, Spec> = {
  "living vs nonliving": { title: "Living vs nonliving", narration: "Living things grow, need food and water, and can reproduce — like a plant or a dog. Nonliving things, like a rock, don't. Let's learn to tell them apart.", bullets: ["Living things grow, eat, reproduce", "Nonliving things don't", "All living things are made of cells"] },
  "plant life cycle": { title: "Plant life cycle", narration: "A plant's life goes seed → sprout → seedling → adult plant → flower → new seeds. A seed needs water, warmth, and air to start growing.", bullets: ["Seed → sprout → adult → flower → seed", "Seeds need water, warmth, and air", "The cycle repeats with new seeds"] },
  "animal life cycles": { title: "Animal life cycles", narration: "Animals grow and change too. Some hatch from eggs; some are born live. A few, like frogs and butterflies, change shape completely — that's metamorphosis.", bullets: ["Some hatch from eggs, some born live", "Metamorphosis = a big body change", "Tadpole → frog, caterpillar → butterfly"] },
  "habitats": { title: "Habitats", narration: "A habitat is the home where an animal or plant lives — desert, ocean, forest. A good habitat gives food, water, shelter, and space to survive.", bullets: ["Habitat = where something lives", "It provides food, water, shelter, space", "Different animals fit different habitats"] },
  "animal groups": { title: "Animal groups", narration: "Animals with backbones split into five groups: mammals, birds, fish, reptiles, and amphibians. Each has clues — fur, feathers, scales, gills.", bullets: ["5 vertebrate groups", "Mammals, birds, fish, reptiles, amphibians", "Clues: fur, feathers, scales, gills"] },

  "food chains": { title: "Food chains", narration: "A food chain shows who eats whom, and energy flows along it — usually starting with a plant (a producer). The arrow points to the eater.", bullets: ["Shows the flow of energy", "Starts with a producer (plant)", "Arrow points to the eater"] },
  "food webs": { title: "Food webs", narration: "A food web is many food chains linked together. Most animals eat more than one thing, so the web shows how everything in an ecosystem connects.", bullets: ["Many food chains linked together", "Most animals eat more than one food", "Remove one species → others are affected"] },
  "producers and consumers": { title: "Producers & consumers", narration: "Producers make their own food using sunlight — that's plants. Consumers can't, so they eat other living things. Everything depends on producers.", bullets: ["Producers make food (plants, sunlight)", "Consumers eat other organisms", "Producers are the base of every web"] },
  "adaptation": { title: "Adaptation", narration: "An adaptation is a feature or behavior that helps an animal survive — a polar bear's thick fur, a camel storing fat, camouflage to hide.", bullets: ["A trait that aids survival", "Physical (fur) or behavioral (migration)", "Helps it fit its habitat"] },

  "water cycle": { title: "Water cycle", narration: "Water moves in a cycle: the sun evaporates it into vapor, it condenses into clouds, then falls as precipitation. Round and round it goes.", bullets: ["Evaporation → condensation → precipitation", "The sun powers the cycle", "Water is reused over and over"] },
  "weather patterns": { title: "Weather patterns", narration: "Weather is the day-to-day state of the air — temperature, clouds, rain, wind. We measure it with tools like thermometers and rain gauges.", bullets: ["Weather = day-to-day air conditions", "Tools: thermometer, rain gauge, anemometer", "Climate is the long-term pattern"] },
  "rocks and minerals": { title: "Rocks & minerals", narration: "There are three rock types: igneous (from cooled lava), sedimentary (pressed layers), and metamorphic (changed by heat and pressure). The rock cycle turns one into another.", bullets: ["Igneous, sedimentary, metamorphic", "Formed by heat, pressure, or layering", "The rock cycle recycles them"] },
  "the solar system": { title: "The solar system", narration: "Eight planets orbit our star, the Sun, held by gravity. Mercury is closest, Jupiter is the biggest, and we live on Earth, the third planet.", bullets: ["8 planets orbit the Sun", "Gravity holds them in orbit", "Order starts: Mercury, Venus, Earth, Mars"] },
  "earth, sun and moon": { title: "Earth, Sun & Moon", narration: "Earth spins to give us day and night, and orbits the Sun once a year. The Moon orbits Earth, and its lit shape changes through phases.", bullets: ["Earth's spin = day and night", "Earth's tilt = the seasons", "The Moon reflects sunlight and has phases"] },

  "solids, liquids, gases": { title: "Solids, liquids, gases", narration: "Matter comes in three states. A solid keeps its shape, a liquid takes the shape of its container, and a gas spreads to fill all the space.", bullets: ["Solid = fixed shape and volume", "Liquid = takes its container's shape", "Gas = fills the whole space"] },
  "state changes": { title: "State changes", narration: "Adding or removing heat changes matter's state. Melting, freezing, evaporating, and condensing all move matter between solid, liquid, and gas.", bullets: ["Heat changes the state of matter", "Melt, freeze, evaporate, condense", "The substance stays the same"] },
  "melting and freezing": { title: "Melting & freezing", narration: "Melting turns a solid into a liquid when it heats up; freezing turns a liquid into a solid when it cools. Water melts and freezes at 0°C.", bullets: ["Melting: solid → liquid (heat)", "Freezing: liquid → solid (cool)", "Water freezes/melts at 0°C"] },
  "evaporation": { title: "Evaporation", narration: "Evaporation is a liquid slowly turning into a gas. A puddle dries up because the water becomes vapor — faster when it's hot and windy.", bullets: ["Liquid → gas", "Happens faster when hot and windy", "It's part of the water cycle"] },

  "cell structure": { title: "Cell structure", narration: "Cells are the building blocks of life. Inside, the nucleus controls the cell, mitochondria make energy, and plant cells add a wall and chloroplasts.", bullets: ["Cells = the building blocks of life", "Nucleus controls; mitochondria power", "Plant cells have a wall + chloroplasts"] },
  "cell functions": { title: "Cell functions", narration: "Each part of a cell has a job. Together they keep the cell alive — taking in nutrients, making energy, and following the instructions in DNA.", bullets: ["Each organelle has a job", "DNA holds the instructions", "Parts work together to stay alive"] },
  "photosynthesis": { title: "Photosynthesis", narration: "Plants make their own food. Using sunlight, carbon dioxide, and water, they produce glucose and release the oxygen we breathe. It happens in the leaves.", bullets: ["Sunlight + CO₂ + water → glucose + oxygen", "Happens in chloroplasts (leaves)", "It makes the oxygen we breathe"] },
  "respiration": { title: "Respiration", narration: "Respiration releases energy from food. Cells use oxygen to break down glucose, giving energy and releasing carbon dioxide and water. It's the opposite of photosynthesis.", bullets: ["Glucose + oxygen → energy + CO₂ + water", "Happens in mitochondria", "Roughly the reverse of photosynthesis"] },
  "human body systems": { title: "Human body systems", narration: "Your body runs on teamwork. The circulatory system pumps blood, the respiratory system breathes, the digestive system breaks down food, and the nervous system controls it all.", bullets: ["Systems work together", "Heart pumps; lungs breathe; brain controls", "Organs → tissues → cells"] },
  "the digestive system": { title: "The digestive system", narration: "Digestion breaks food into nutrients your body can use. It travels mouth → esophagus → stomach → intestines, where nutrients pass into the blood.", bullets: ["Breaks food into nutrients", "Mouth → esophagus → stomach → intestines", "Small intestine absorbs nutrients"] },

  "elements and compounds": { title: "Elements & compounds", narration: "An element is made of one kind of atom — like oxygen or gold. A compound is two or more elements joined, like water (H₂O). The periodic table lists every element.", bullets: ["Element = one kind of atom", "Compound = elements joined (H₂O)", "Atoms are the building blocks"] },
  "chemical reactions": { title: "Chemical reactions", narration: "In a chemical reaction, substances rearrange into new ones — like rust forming or wood burning. Signs include color change, gas, heat, or light.", bullets: ["Substances turn into new substances", "Signs: color change, gas, heat, light", "Atoms are rearranged, not lost"] },
  "acids and bases": { title: "Acids & bases", narration: "The pH scale (0–14) tells how acidic or basic something is. Below 7 is acidic (lemon juice), above 7 is basic (soap), and 7 is neutral (water).", bullets: ["pH scale runs 0–14", "Under 7 acidic, over 7 basic, 7 neutral", "Acid + base neutralize each other"] },
  "periodic table basics": { title: "Periodic table basics", narration: "The periodic table organizes all the elements by atomic number. Columns (groups) share similar properties; each element has a one- or two-letter symbol.", bullets: ["Organized by atomic number", "Columns (groups) share properties", "Each element has a symbol (Na, O, Fe)"] },

  "forces and motion": { title: "Forces & motion", narration: "A force is a push or a pull that can start, stop, or change motion. Newton's laws explain how. Unbalanced forces make things speed up, slow down, or turn.", bullets: ["Force = a push or a pull", "It changes an object's motion", "Friction and gravity are forces"] },
  "energy": { title: "Energy", narration: "Energy is the ability to do work, and it comes in forms — kinetic (motion) and potential (stored). It can change form but is never created or destroyed.", bullets: ["Kinetic = motion; potential = stored", "Energy changes form", "It's never created or destroyed"] },
  "waves and sound": { title: "Waves & sound", narration: "Waves carry energy. Sound is a wave made by vibrations — it needs a material to travel through, so it can't move through empty space.", bullets: ["Waves carry energy", "Sound comes from vibrations", "Sound can't travel through a vacuum"] },
  "simple machines": { title: "Simple machines", narration: "Simple machines make work easier by changing a force — the lever, pulley, wheel and axle, inclined plane, wedge, and screw. A ramp is an inclined plane.", bullets: ["6 simple machines", "They change the size/direction of a force", "Ramp = inclined plane; seesaw = lever"] },
  "electricity": { title: "Electricity", narration: "Electricity flows through a complete circuit. Conductors like metal let it flow; insulators like rubber stop it. A switch opens or closes the path.", bullets: ["Needs a complete (closed) circuit", "Conductors carry it; insulators block it", "A switch opens/closes the circuit"] },
};

const TABLES: Record<string, Record<string, Spec>> = { R: READING, W: WRITING, S: SCIENCE };

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

const GENERIC: Record<string, Spec> = {
  R: { title: "Reading skill", narration: "Before you practice, here's the idea behind this skill. Read carefully, look for clues, and take your time. You've got this.", bullets: ["Read carefully and look for clues", "Take your time", "Check your answer makes sense"] },
  W: { title: "Writing skill", narration: "Before you practice, here's the idea. Strong writing is clear and correct. Think about your reader as you go.", bullets: ["Be clear and correct", "Think about your reader", "Re-read to check your work"] },
  S: { title: "Science skill", narration: "Before you practice, here's the idea behind this topic. Observe, think about why, and use what you learn. Let's explore.", bullets: ["Observe carefully", "Ask why it happens", "Use evidence to decide"] },
};

/** Per-skill lesson for a non-math skill, or null if not Reading/Writing/Science. */
export function nonMathConcept(levelCode: string | undefined, skillName: string): ConceptTutorial | null {
  const sub = (levelCode ?? "").trim().charAt(0).toUpperCase();
  const table = TABLES[sub];
  if (!table) return null;
  const key = skillName.trim().toLowerCase();
  const spec = table[key] ?? GENERIC[sub];
  return {
    id: `${sub.toLowerCase()}-${slug(key)}`, // stable per skill → lesson shows once per skill
    title: spec.title,
    visual: VISUAL[sub],
    narration: spec.narration,
    bullets: spec.bullets,
  };
}
