// src/app/layout.tsx
import type { Metadata } from "next";
import "@/styles/globals.css";
import { Providers } from "./providers";
import { GdprBanner } from "@/components/GdprBanner";

export const metadata: Metadata = {
  metadataBase: new URL('https://eduyro.com'),
  title: {
    default: "Eduyro — Mastery learning, one step at a time",
    template: "%s · Eduyro",
  },
  description:
    "Eduyro is a print-first, mastery-based learning platform for Pre-K to Grade 12. Daily worksheets in Math, Reading, Writing, and Science. Used by students, parents, and schools.",
  keywords: [
    "math worksheets", "kumon alternative", "printable worksheets",
    "homeschool curriculum", "school tutoring platform", "mastery learning",
    "reading comprehension", "writing practice",
  ],
  authors: [{ name: "Eduyro Education" }],
  openGraph: {
    type: "website",
    siteName: "Eduyro",
    title: "Eduyro — Mastery learning, one step at a time",
    description: "Daily worksheets · AI placement · Print-first curriculum from Pre-K to Grade 12.",
    // Social card generated by src/app/opengraph-image.tsx — no static file needed.
  },
  twitter: {
    card: "summary_large_image",
    title: "Eduyro",
    description: "Mastery learning, one worksheet at a time.",
  },
  robots: { index: true, follow: true },
  alternates: { canonical: "/" },
  // Set GOOGLE_SITE_VERIFICATION in env to the token from Google Search Console
  // → Next renders <meta name="google-site-verification" …> so you can verify
  // ownership and submit the sitemap.
  verification: process.env.GOOGLE_SITE_VERIFICATION
    ? { google: process.env.GOOGLE_SITE_VERIFICATION }
    : undefined,
};

// Structured data — helps Google understand the site (Organization + WebSite + Product).
// priceValidUntil is refreshed each deploy (~1 year out) so the offer never reads stale.
const PRICE_VALID_UNTIL = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000)
  .toISOString()
  .slice(0, 10);

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://eduyro.com/#org",
      name: "Eduyro Education",
      url: "https://eduyro.com",
      description:
        "Print-first, mastery-based learning for Pre-K to Grade 12 — daily worksheets in Math, Reading, Writing, and Science.",
      sameAs: [] as string[],
    },
    {
      "@type": "WebSite",
      "@id": "https://eduyro.com/#website",
      url: "https://eduyro.com",
      name: "Eduyro",
      publisher: { "@id": "https://eduyro.com/#org" },
    },
    {
      "@type": "Product",
      "@id": "https://eduyro.com/shop#product",
      name: "Eduyro Printable Math Worksheet Packs",
      description:
        "100-worksheet printable PDF packs per math skill (Addition through Polynomials), with answer keys. A Kumon-style mastery program at a fraction of the price.",
      image: "https://eduyro.com/opengraph-image",
      brand: { "@id": "https://eduyro.com/#org" },
      category: "Educational Worksheets",
      offers: {
        "@type": "AggregateOffer",
        priceCurrency: "USD",
        lowPrice: "4.99",
        highPrice: "27.99",
        offerCount: 15,
        priceValidUntil: PRICE_VALID_UNTIL,
        availability: "https://schema.org/InStock",
        url: "https://eduyro.com/shop",
      },
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
        <Providers>{children}</Providers>
        <GdprBanner />
      </body>
    </html>
  );
}
