// src/lib/reading/word-items.ts
// TRACK A word-level practice — the decoding half of an early reading session.
//
// A phonics session is word work THEN decodable text. The text is in
// ./decodable-texts.ts; this file is the word work. Every item is generated
// from the stage's own word lists, so a child is only ever asked about patterns
// they have been taught (./phonics.ts), and every distractor is checked against
// the decodability rules so a wrong answer is never an undecodable word the
// child couldn't have read either way.
//
// Item types (all auto-gradable, all real phonics practice):
//   • real vs nonsense    — proves DECODING, not memorised word shapes
//   • rhyme / word family  — hearing the rime unit
//   • same beginning sound — onset isolation
//   • one-sound swap       — the word-chain routine (sat → mat), the single
//                            highest-value blending exercise there is
//   • sound counting       — phoneme segmentation

import {
  cumulativeSampleWords, getStage, type StageId,
} from "./phonics";
import { judgeWord } from "./decodability";

export interface WordItem {
  question: string;
  options: string[];
  answer: string;
}

/** Deterministic per (stage, sheet) so a child's sheet is stable on reload. */
function rng(seed: number) {
  let s = seed >>> 0 || 1;
  return () => ((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296);
}
const pick = <T,>(arr: T[], r: () => number): T => arr[Math.floor(r() * arr.length)];
function shuffle<T>(arr: T[], r: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(r() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}

/** The rime = from the first vowel to the end ("cat" → "at"). Drives rhyme. */
function rime(word: string): string {
  const i = word.search(/[aeiou]/);
  return i < 0 ? word : word.slice(i);
}
/** The onset = everything before the first vowel ("ship" → "sh"). */
function onset(word: string): string {
  const i = word.search(/[aeiou]/);
  return i <= 0 ? "" : word.slice(0, i);
}

// CURATED non-words, per stage. These are deliberately NOT generated by
// recombining onsets and rimes: that approach silently produces (a) real words,
// which breaks the "which is a real word?" item, and (b) profanity — "f" + the
// rime of "duck" is the obvious one. In a product used by six-year-olds that is
// not a risk worth taking for the sake of variety. Each entry below is checked
// by scripts/audit-word-items.ts to be decodable at its stage.
const NONSENSE: Record<StageId, string[]> = {
  "cvc-a": ["vab", "jat", "zad", "yad", "vam", "jaz"],
  "cvc-iou": ["zub", "jub", "vog", "yut", "vun", "zog"],
  "cvc-e-review": ["jeb", "zem", "ved", "yeb", "zen", "vex"],
  "digraphs": ["shet", "chun", "thop", "vick", "jich", "shup"],
  "blends-initial": ["flad", "stum", "blad", "crin", "glop", "prat"],
  "blends-final": ["hilp", "nast", "belk", "jund", "vamp", "zilt"],
  "vce": ["vope", "zike", "jate", "yune", "vube", "zade"],
  "vowel-teams-long": ["voat", "zeek", "jain", "yeal", "voon", "zay"],
  "r-controlled": ["vurn", "zorm", "jarn", "yirl", "verd", "zark"],
  "diphthongs": ["voin", "zoud", "jaw", "yoy", "vout", "zoil"],
  "suffixes": ["vabs", "jating", "zomped", "yunning", "veps", "zilts"],
};

function nonsenseWords(stage: StageId, realWords: Set<string>): string[] {
  return (NONSENSE[stage] ?? []).filter(
    (w) => !realWords.has(w) && judgeWord(w, stage).decodable,
  );
}

export function generateWordItems(stage: StageId, count: number, seed = 1): WordItem[] {
  const st = getStage(stage);
  if (!st) return [];
  const r = rng(seed * 7919 + st.order * 104729);
  const words = [...new Set(cumulativeSampleWords(stage))].filter((w) => judgeWord(w, stage).decodable);
  if (words.length < 4) return [];
  const realSet = new Set(words);
  const nonsense = nonsenseWords(stage, realSet);
  const items: WordItem[] = [];

  // 1. Real vs nonsense — the cleanest proof a child is decoding, not guessing.
  for (const nw of nonsense.slice(0, 3)) {
    const real = pick(words, r);
    const others = shuffle(nonsense.filter((n) => n !== nw), r).slice(0, 2);
    if (others.length < 2) break;
    items.push({
      question: `Which one is a REAL word?`,
      options: shuffle([real, nw, ...others], r),
      answer: real,
    });
  }

  // 2. Rhyme / word family — same rime unit.
  // Practise THIS stage's new pattern first — a magic-e lesson whose items are
  // all short-a words from three stages ago isn't teaching magic e.
  const focus = new Set(st.sampleWords.filter((w) => judgeWord(w, stage).decodable));
  const focusFirst = <T,>(entries: [string, string[]][]) =>
    entries.sort((a, b) => Number(b[1].some((w) => focus.has(w))) - Number(a[1].some((w) => focus.has(w))));

  const byRime = new Map<string, string[]>();
  for (const w of words) {
    const k = rime(w);
    byRime.set(k, [...(byRime.get(k) ?? []), w]);
  }
  for (const [k, group] of focusFirst([...byRime.entries()].filter(([, g]) => g.length >= 2)).slice(0, 3)) {
    const [a, b] = shuffle(group, r);
    const wrong = shuffle(words.filter((w) => rime(w) !== k), r).slice(0, 3);
    if (wrong.length < 3) continue;
    items.push({
      question: `Which word rhymes with "${a}"?`,
      options: shuffle([b, ...wrong], r),
      answer: b,
    });
  }

  // 3. Same beginning sound — onset isolation.
  const byOnset = new Map<string, string[]>();
  for (const w of words) {
    const o = onset(w);
    if (o) byOnset.set(o, [...(byOnset.get(o) ?? []), w]);
  }
  for (const [o, group] of focusFirst([...byOnset.entries()].filter(([, g]) => g.length >= 2)).slice(0, 3)) {
    const [a, b] = shuffle(group, r);
    const wrong = shuffle(words.filter((w) => onset(w) !== o), r).slice(0, 3);
    if (wrong.length < 3) continue;
    items.push({
      question: `Which word starts with the same sound as "${a}"?`,
      options: shuffle([b, ...wrong], r),
      answer: b,
    });
  }

  // 4. One-sound swap (word chains) — the core blending routine.
  for (const [k, group] of focusFirst([...byRime.entries()].filter(([, g]) => g.length >= 2)).slice(0, 3)) {
    const [from, to] = shuffle(group, r);
    const fromOnset = onset(from), toOnset = onset(to);
    if (!fromOnset || !toOnset || fromOnset === toOnset) continue;
    const wrong = shuffle(words.filter((w) => w !== to && w !== from), r).slice(0, 3);
    if (wrong.length < 3) continue;
    items.push({
      question: `Change the "${fromOnset}" in "${from}" to "${toOnset}". What word do you get?`,
      options: shuffle([to, ...wrong], r),
      answer: to,
    });
  }

  // 5. Sound counting — phoneme segmentation (graphemes = sounds).
  for (const w of shuffle([...focus, ...words], r).slice(0, 3)) {
    const g = judgeWord(w, stage).graphemes;
    if (!g) continue;
    const n = g.length;
    if (n < 2 || n > 5) continue;
    const opts = [...new Set([n, n + 1, Math.max(1, n - 1), n + 2])].slice(0, 4).map(String);
    if (opts.length < 4) continue;
    items.push({
      question: `How many sounds do you hear in "${w}"?`,
      options: shuffle(opts, r),
      answer: String(n),
    });
  }

  return shuffle(items, r).slice(0, count);
}
